### PR TITLE
Fix of listing certificates with applied filters

### LINKED ISSUE #266: Filter of certificates does not work and returns server error
When requesting list of certificates with some filter, it returns server error, with record in logs:

`Unable to perform requested lazy initialization [com.czertainly.core.dao.entity.CertificateContent.content] - session is closed and settings disallow loading outside the Session`

Search service in dynamic search query uses directly native queries and is trying to access association outside of hibernate session. Search should be rewritten with predicates to work in scope of Hibernate.

### PR DESCRIPTION
**Pull request by moro-lukasrejha**
Closes #266

### CODE REVIEW

**Comment by moro-lukasrejha** [comment]
#266 CZERTAINLY-Core #266

**Comment by moro-lukasrejha** [comment]
Closed CZERTAINLY-Core #266

**Comment by moro-lukasrejha** [comment]
close #266

**Comment by moro-lukasrejha** [comment]
Closes #266

**Review by lubomirw — APPROVED** [review]

**Pull request merged**
